# Generated by Django 3.0.7 on 2020-06-29 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logcollection_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcollection',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
